default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: welcome

development:
  <<: *default
  database: trackr

test:
  <<: *default
  database: trackr_test

production:
  <<: *default
  database: trackr_prod
